### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by griffins07** [Qballl/WildernessTp#101]
Not really a bug but the link on your spigot page to the addon that helps teleport players to a main world when using /wild from a spawn world is not working.

**Comment by Qballl** [comment]
Oh b/c I am dumb and forgot to take that out as it's no longer need. That functionality has been built into the plugins now. Here is an example of how 
```
regions:
  playing_world_name:
    minX: num
    maxX: num
    minZ: num
    maxZ: num
  spawn_world_name:
    worldTo: "playing_world_name"
```
