### ISSUE TITLE
[Question] World section of config.

### ISSUE THREAD

**Issue by Castiella** [Qballl/WildernessTp#75]
I want people in my Hub world to run /wild and be sent to the smp14 world. I cant seem to get my head around the config. I don't think I've done it right... Could you advise?

Pastebin: https://pastebin.com/zRyXNz6C

**Comment by Castiella** [comment]
https://pastebin.com/ypUSCaBm

i've also tried this

**Comment by Qballl** [comment]
The WorldTo belongs in the same area as the mins and maxs

**Comment by Castiella** [comment]
Sorry I'm confused.

You mean like

Worlds:
   world: Hub
      WorldTo: "smp14"

?

**Comment by Qballl** [comment]
Did you get it fixed?

**Comment by RonaldBunk** [comment]
@Castiella The correct syntax is:
```
Worlds:
   world:
      minX: -5000
      maxX: 5000
      minZ: -5000
      maxZ: 5000
      InvertY: true
   worldA:
      WorldTo: worldB
   worldB:
      minX: -1000
      maxX: 1000
      minZ: -1000
      maxZ: 1000
```
